package com.hydra.apex;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.text.InputType;import android.view.*;import android.webkit.*;import android.widget.*;import java.nio.charset.StandardCharsets;import java.security.*;import javax.crypto.*;import javax.crypto.spec.GCMParameterSpec;import android.security.keystore.KeyProperties;import android.security.keystore.KeyGenParameterSpec;import android.util.Base64;

public class MainActivity extends Activity {
    LinearLayout root, body; TextView status; android.content.SharedPreferences prefs; WebView web;
    int bg=Color.rgb(9,13,20), panel=Color.rgb(17,23,34), text=Color.rgb(243,246,250), muted=Color.rgb(137,148,166), accent=Color.rgb(69,215,167), warn=Color.rgb(243,181,98);
    @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("hydra",0); showShell(); showHome();}
    TextView tv(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(text);v.setTextSize(sp);v.setPadding(16,12,16,12);return v;}
    Button btn(String s){Button x=new Button(this);x.setText(s);x.setTextColor(text);return x;}
    void showShell(){setContentView(com.hydra.apex.R.layout.activity_main); root=findViewById(R.id.content); ((Button)findViewById(R.id.home)).setOnClickListener(v->showHome());((Button)findViewById(R.id.apex)).setOnClickListener(v->showPage("APEX CORE","5m regime → 3m breakout/retest → 1m trigger. PAPER execution only."));((Button)findViewById(R.id.trades)).setOnClickListener(v->showPage("TRADES","Live broker orders are not enabled. Connect the PAPER dashboard to review the journal."));((Button)findViewById(R.id.broker)).setOnClickListener(v->showBroker());((Button)findViewById(R.id.settings)).setOnClickListener(v->showSettings());}
    void base(String title,String sub){root.removeAllViews();LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(16,8,16,20);TextView h=tv(title,27);h.setTypeface(null,1);l.addView(h);TextView s=tv(sub,14);s.setTextColor(muted);l.addView(s);root.addView(l);body=l;}
    TextView card(String a,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(8,8,8,8);c.setBackgroundColor(panel);TextView x=tv(a,14);x.setTypeface(null,1);c.addView(x);TextView y=tv(b,13);y.setTextColor(muted);c.addView(y);body.addView(c,new LinearLayout.LayoutParams(-1,-2){ {setMargins(0,8,0,0);} });return y;}
    void showHome(){base("Command Center","Production-style shell • safety-first • no live money");card("STATUS","PAPER_READY • DEMO / configurable live-data bridge");card("RISK","₹15,000 capital • hard trade cap ₹375 • daily guard ₹600 • max 2 trades");card("APEX CORE","5m regime → 3m breakout/retest → 1m trigger");card("EXECUTION","Paper buy at ask → paper sell at bid • TRUE NET P&L");Button open=btn("OPEN HYDRA WEB DASHBOARD");open.setOnClickListener(v->openWeb());body.addView(open,new LinearLayout.LayoutParams(-1,60));}
    void showPage(String t,String d){base(t,d);card("SAFETY","LIVE execution remains locked in this Android build.");card("DATA","No synthetic market metrics are shown.");card("NEXT","Use Broker Setup to configure the local HYDRA connection.");}
    void showBroker(){base("Broker Setup","5paisa fields are stored locally on this phone. They are not invented or prefilled.");edit("5paisa App Key","app_key");edit("User ID","user_id");edit("Encryption Key","encryption_key");edit("Access Token","access_token");edit("Client Code","client_code");edit("HYDRA URL","base_url", "http://127.0.0.1:8181");Button save=btn("SAVE LOCALLY");save.setOnClickListener(v->{saveFields();toast("Saved locally. Broker execution is still locked.");});body.addView(save,new LinearLayout.LayoutParams(-1,60));Button webb=btn("OPEN LOCAL HYDRA DASHBOARD");webb.setOnClickListener(v->openWeb());body.addView(webb,new LinearLayout.LayoutParams(-1,60));}
    java.util.HashMap<String,EditText> fields=new java.util.HashMap<>();
    void edit(String label,String key){edit(label,key,"");}
    void edit(String label,String key,String def){TextView l=tv(label,13);l.setTextColor(muted);body.addView(l);EditText e=new EditText(this);e.setTextColor(text);e.setHintTextColor(muted);e.setHint("Enter "+label);e.setSingleLine(true);e.setText(key.equals("base_url")?prefs.getString(key,def):decrypt(prefs.getString(key,"")));if(key.contains("key")||key.contains("token"))e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);body.addView(e,new LinearLayout.LayoutParams(-1,58));fields.put(key,e);}
    void saveFields(){for(String k:fields.keySet())prefs.edit().putString(k, k.equals("base_url")?fields.get(k).getText().toString():encrypt(fields.get(k).getText().toString())).apply();}
    void showSettings(){base("Settings","Safety controls are intentionally locked from the Android shell.");card("MODE","PAPER (locked)");card("LIVE ENABLED","false (locked)");card("STATIC IP","Not confirmed (locked)");card("ALGO ID","0 / not configured");card("ADAPTIVE","Shadow-only by default");}
    void openWeb(){String u=prefs.getString("base_url","http://127.0.0.1:8181");web=new WebView(this);web.setBackgroundColor(bg);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.setWebViewClient(new WebViewClient());web.loadUrl(u);setContentView(web);}
    String encrypt(String s){try{KeyStore ks=KeyStore.getInstance("AndroidKeyStore");ks.load(null);if(!ks.containsAlias("hydra_key")){KeyGenerator kg=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");kg.init(new KeyGenParameterSpec.Builder("hydra_key",KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());kg.generateKey();}SecretKey k=((KeyStore.SecretKeyEntry)ks.getEntry("hydra_key",null)).getSecretKey();Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,k);byte[] iv=c.getIV(),ct=c.doFinal(s.getBytes(StandardCharsets.UTF_8));return Base64.encodeToString(iv,2)+":"+Base64.encodeToString(ct,2);}catch(Exception e){return "";}}
    String decrypt(String s){try{if(s==null||s.isEmpty())return "";String[] p=s.split(":",2);KeyStore ks=KeyStore.getInstance("AndroidKeyStore");ks.load(null);SecretKey k=((KeyStore.SecretKeyEntry)ks.getEntry("hydra_key",null)).getSecretKey();Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,k,new GCMParameterSpec(128,Base64.decode(p[0],2)));return new String(c.doFinal(Base64.decode(p[1],2)),StandardCharsets.UTF_8);}catch(Exception e){return "";}}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else{web=null;showShell();showHome();}}
}
